import { Manrope, Poppins } from "next/font/google";

import Footer from "./components/global/Footer";
import Navbar from "./components/global/Navbar";
import RightContactRailGlobal from "../app/components/rails/RightContactRail"; // ⬅️ add this
import "./styles/globals.css";

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["300", "400", "500", "600"],
});

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300"],
});

export const metadata = {
  title: "Quality Team Solutions",
  description: "Generated by create next app",
  icons: { icon: "/images/2.png" },
};

export default function RootLayout({ children }) {
  const year = new Date().getFullYear();

  return (
    <html lang="en" className={`${manrope.variable} ${poppins.variable}`}>
      <body>
        {/* ✅ Navbar always on top, global */}
        <Navbar />

        {/* Page-specific content */}
        {children}

        {/* ✅ Global WhatsApp rail on all pages except "/" */}
        <RightContactRailGlobal
          phone="+971 56 806 8070"
          whatsappHref="https://wa.me/971568068070"
          footerSelector="footer"
        />


        {/* ✅ Footer always at bottom */}
        <Footer year={year} />
      </body>
    </html>
  );
}
